FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copia a pasta app inteira
COPY app/ ./app/

RUN useradd --create-home appuser && chown -R appuser:appuser /app
USER appuser

HEALTHCHECK CMD python -c "import redis; r=redis.Redis(host='redis'); r.ping()"

CMD ["python", "-m", "app.worker.worker"]
